version: 0.0
os: linux

files:
  - source: /                          # files to be copied
    destination: /home/ubuntu/app  
    overwrite: yes    

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/pull_image.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 60
      runas: ubuntu

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 60
      runas: ubuntu
