version: 0.2

env:
  variables:
    TERRAFORM_WORKING_DIR: terraform-infra/envs/dev
    AWS_DEFAULT_REGION: ap-south-1
  parameter-store:
    TF_VAR_file: "/dev/terraform/dev_tfvars"
    BUCKET_NAME: "/dev/s3_bucket_name"
    DYNAMODB_TABLE: "/dev/dynamodb_table_name"
    KMS_KEY_ARN: "/dev/kms_key_arn"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update && apt-get install -y unzip curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update && apt-get install terraform -y

  pre_build:
    commands:
      - cd $TERRAFORM_WORKING_DIR
      - |
        cat > backend.tf <<EOF
        terraform {
          backend "s3" {
            bucket         = "${BUCKET_NAME}"
            key            = "dev/terraform.tfstate"
            region         = "${AWS_DEFAULT_REGION}"
            dynamodb_table = "${DYNAMODB_TABLE}"
            encrypt        = true
            kms_key_id     = "${KMS_KEY_ARN}"
          }
        }
        EOF
      - terraform init -input=false
      - echo "Importing existing ALB..."
      - terraform import module.alb.aws_lb.app_alb arn:aws:elasticloadbalancing:ap-south-1:345594588323:loadbalancer/app/dev-alb/bd9cd20d111ff758 || echo "ALB already imported or not required"

      - echo "Importing Target Group Blue..."
      - terraform import module.alb.aws_lb_target_group.app_tg_blue arn:aws:elasticloadbalancing:ap-south-1:345594588323:targetgroup/dev-tg-blue/e97a9d51960457f8 || echo "TG Blue already imported or not required"

      - echo "Importing Target Group Green..."
      - terraform import module.alb.aws_lb_target_group.app_tg_green arn:aws:elasticloadbalancing:ap-south-1:345594588323:targetgroup/dev-tg-green/0e2994f7893a8640 || echo "TG Green already imported or not required"


  build:
    commands:
      - printf "%s\n" "$TF_VAR_file" > dev_tfvars
      - echo "Decoded tfvars file:"
      - cat dev_tfvars
      - terraform plan -input=false -var-file=dev_tfvars -out=tfplan
      - terraform apply -input=false -var-file=dev_tfvars -auto-approve tfplan

artifacts:
  files:
    - '**/*'
